# Generated by Django 5.1 on 2024-08-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_platform", "0002_remove_content_created_at_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("N", "N/A"),
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                ],
                default="N",
                max_length=1,
                null=True,
            ),
        ),
    ]
